### ISSUE TITLE
Write Serializer Classes And Complete Api Managers

### ISSUE THREAD

**Issue by atulsingh029** [atulsingh029/e-learning-platform#12]
files : 
`api/serializers.py`
`management/views.py`

**Comment by abhishekjaiscs18** [comment]
please describe the task in management/views.py

**Comment by atulsingh029** [comment]
All implementations are wrong, read requirement properly

**Comment by atulsingh029** [comment]
bhai 4 the, 2 maine kr diye the , 2krne the usme ek kiye ho wo bhi serialize kiye bina return kr diye.
Total 1 line likhe ho, isiliye iss commit ko delete kr rha hu mai
