### ISSUE TITLE
TimeTable Management System

### ISSUE THREAD

**Issue by atulsingh029** [atulsingh029/e-learning-platform#15]
**You have to design and implement time table management system**

We already have a database setup in our project so,
Our project has rooms in it and  every room needs time table so for that i will add a new table in database with name Timetable and add a foreign key to room table, `You have to tell what other fields you need, if you need any other table for it as well in support specify that also`
once you give the schema of database, I'll create required table in database and specify a python file in which you can develop the system.

**Comment by abhishekjaiscs18** [comment]
[time table db.pdf](https://github.com/atulsingh029/e-learning-platform/files/5064734/time.table.db.pdf)
